apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inferencedb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "inferencedb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "inferencedb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "inferencedb.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "inferencedb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: INFERENCEDB_KAFKA_BROKER
              value: {{ .Values.kafka.broker | quote }}
            - name: INFERENCEDB_KAFKA_SCHEMA_REGISTRY_URL
              value: {{ .Values.kafka.schemaRegistryUrl | quote }}
            - name: INFERENCEDB_KAFKA_CONNECT_URL
              value: {{ .Values.kafka.connectUrl | quote }}
            - name: INFERENCEDB_LOG_LEVEL
              value: {{ .Values.logLevel }}
            - name: INFERENCEDB_CONFIG_PROVIDER
              value: {{ .Values.inferencedb.configProvider.type | quote }}
            - name: INFERENCEDB_CONFIG_PROVIDER_ARGS
              value: {{ .Values.inferencedb.configProvider.args | toJson | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
