{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if .Values.rbac.namespaced }}RoleBinding{{ else }}ClusterRoleBinding{{ end }}
metadata:
  name: {{ include "inferencedb.fullname" . }}
  {{ if .Values.rbac.namespaced }}namespace: {{ .Release.Namespace }}{{ end }}
  labels:
    {{- include "inferencedb.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if .Values.rbac.namespaced }}Role{{ else }}ClusterRole{{ end }}
  name: {{ include "inferencedb.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "inferencedb.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
