apiVersion: v1
kind: Service
metadata:
  name: {{ include "inferencedb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "inferencedb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6066
      protocol: TCP
      name: faust
  selector:
    {{- include "inferencedb.selectorLabels" . | nindent 4 }}
