{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "inferencedb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "inferencedb.labels" . | nindent 4 }}
    {{- if .Values.serviceMonitor.selector }}
    {{- toYaml .Values.serviceMonitor.selector | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "inferencedb.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
