apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: inferenceloggers.inferencedb.aporia.com
spec:
  scope: Namespaced
  group: inferencedb.aporia.com
  names:
    kind: InferenceLogger
    plural: inferenceloggers
    singular: inferencelogger
    shortNames:
      - inflog
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                topic:
                  type: string
                schemaProvider:
                  type: object
                  properties:
                    type:
                      type: string
                    config:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                eventProcessor:
                  type: object
                  properties:
                    type:
                      type: string
                    config:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                destination:
                  type: object
                  properties:
                    type:
                      type: string
                    config:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
