name: Deploy
on:
  push:
    branches:
      - main
      - kubernetes-api-url
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git
        run: |
          git config --global user.email "camparibot@aporia.com"
          git config --global user.name "camparibot"
          git config --global push.followTags true

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: make install-deps

      - name: Bump Version
        id: bump-version
        run: make bump-version
        env:
          IMAGE_NAME: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          CAMPARIBOT_TOKEN: ${{ secrets.CAMPARIBOT_TOKEN }}

      - name: Create check run
        id: create-check-run
        run: |
          CHECK_RUN_ID=`curl -X POST https://api.github.com/repos/${{ github.repository }}/check-runs \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept:application/vnd.github.antiope-preview+json" \
              -d "{\"name\": \"Aporia / deploy (push)\", \"head_sha\": \"${{ steps.bump-version.outputs.bumped_version_commit_hash }}\", \"status\": \"in_progress\", \"details_url\": \"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\", \"output\": {\"title\": \"Versioned Commit\", \"summary\": \"This is a versioned commit. To see the full GitHub Action, [click here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).\"}}" \
            | jq .id`;
          echo "::set-output name=check_run_id::$CHECK_RUN_ID";

      - name: Cache skaffold image builds & config
        id: cache-skaffold
        uses: actions/cache@v2
        with:
          path: ~/.skaffold/
          key: fixed-${{ github.sha }}
          restore-keys: |
                    fixed-${{ github.sha }}
                    fixed-

      - name: Build
        run: make build
        env:
          NEW_VERSION: ${{ steps.bump-version.outputs.new-version }}
          CAMPARIBOT_TOKEN: ${{ secrets.CAMPARIBOT_TOKEN }}

      - name: Update check run to success
        run: |
          curl -X PATCH https://api.github.com/repos/${{ github.repository }}/check-runs/${{ steps.create-check-run.outputs.check_run_id }} \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept:application/vnd.github.antiope-preview+json" \
            -d "{\"status\": \"completed\", \"conclusion\": \"success\"}";
